travis:
  secure:
    BINSTAR_TOKEN: Iekz8zj+vddz2ixZvZbkSeHy59qFY1CYz1Z1tdg/GSNUBb9CqI8u82LBEhIT+CblUb04kfuL/6EQS5uhH4KhKYoFd6QeWd427WTxCcXpCWN1yzc+Ck5Fsz2EceAnwEOS46MfcJLztgiHicALRFHO6QsmsxTR+ErdfdcT/MO1UmCSjhA0Eybd4nEtKBOk1S6gSIV9wAskLPM0pdDdewDT055BdNS3ZEknrTuXCQRwt8yXEzYgtS8VtIzd1s5X2+wSdwV1XXw+vsVnKChmAUrloIPy3aMol6dc44ff/NnFNaLjHPWUT8b9q8lCruT6hUGqCUKMXE8VS/lrzY68o+qPOpxEUbV96CTc10RwVh7CCQEyiiIjd+rQBlSCVLrt+EqFgxDsfRvUDGYSHZfNrfi2kQ26bC9HpNM8IZXXVEiyqY0zBe1keprX7KAQ0B9MNxDqoJKVtraQ5SGTLjyF4Q2E5HXA9vVZsIK397PdvApOkVEGWxHw6hDG6aPmLu3wI3aEPzT+34byfQyJ2VwdsTkv8n176tTFZT+iED0xm75xAS8ZX6a83n6SH+D80XC6k55PsYwzRTJgHtvMCXCGcCCxWceEUCMWRMcWUUWRFbN77apmAsXOqg7+AUqIpvhr0br4YbmBk4Wocre6ibPJMf5sBSIrCqZPJ14SAOcibaAGNvE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
